### ISSUE TITLE
Gulp tasks search for less files, but should look for scss files

### ISSUE THREAD

**Issue by StSenf** [PaulPoot/pinnacle#1]
Hi there Paul,

i did try to use your October CMS Theme. But when I invoke a Gulp Task, it is searching for less files to create the main.css. E.g. I do get such a error message:

partials/masthead.less' wasn't found.

There is a _masthead.scss file in the styles directory though. How can I change the Gulp Tasks to search for SCSS files instead of LESS files. Do you have any idea what might be wrong?

Cheers and thanks for your theme anyway!

**Comment by paulpoot** [comment]
Hey derhulm,

What version of Node are you using? I'm aware of a Node.js bug. You could try updating gulp-if (`npm update gulp-if`) or downgrading to Node.js 4.4.4, though that is not really a solution. Can you let me know if updating gulp-if fixes your issue?

**Comment by StSenf** [comment]
Hey Paul,

my Node Version is 6.9.1
I did use the update command in the folder where your theme files are located. After hitting this if-command, nothing happend. So I guess there was nothing to update. (Just to be sure, the global gulp installation was just fresh, I extra installed gulp globally to work with your theme.)

So you think the only remaining option would be to downgrad my node?

**Comment by paulpoot** [comment]
Hi derhulm,

Can you enter `npm list gulp-if` in your terminal and send me the result? It should return the current version of gulp-if if it's installed correctly.

**Comment by StSenf** [comment]
Hey,

this is the result: `-- gulp-if@1.2.5
while running this command, this shows: info using node@6.9.1

**Comment by paulpoot** [comment]
All right, so gulp-if is installed correctly. Can you try replacing this line in package.json:

`"gulp-if": "^1.2.5",`

With this line:

 `"gulp-if": "^2.0.2",`

And then running `npm install` when you've saved it. That should update gulp-if.

**Comment by StSenf** [comment]
Hi Paul,

sorry for getting back so late to you. But yes - replacing the line in package.json did the trick. Now the Gulp Task runs without error and a main.css file is created - thank you very much :)

**Comment by paulpoot** [comment]
Good to hear that your issue is fixed! I'll update the package.json to make sure the correct version of gulp-if is installed.
