### ISSUE TITLE
Gulp Watch 

### ISSUE THREAD

**Issue by Michael-Reich** [PaulPoot/pinnacle#2]
Hi Paul,

when I run Gulp Watch locally it opens a new window and nothing is displayed. Do I need to run OctoberCMS in Mamp locally?

I want to use browsersync to develop my theme locally and just push the needed files to my git.

Best, Michael

**Comment by paulpoot** [comment]
Hi Michael,

Yes, you should run OctoberCMS locally through MAMP for example. Once you've got it running, you should open src/manifest.json and change the devUrl to the url your website is running on. For example, if your site is available on localhost/mysite, you should set devUrl to "http://localhost/mysite".

Can you let me know if it works?
