### ISSUE TITLE
Not running bootstrap.js

### ISSUE THREAD

**Issue by caboose014** [PaulPoot/pinnacle#3]
Im not sure if its something I'm doing wrong, but I am unable to get this theme to run the bootstrap.js file. Whenever I create a navbar, when collapsed the toggle button does not work. However, if I add in the bootstrap.js CDN link, everything behaves as normal.

**Comment by paulpoot** [comment]
Hi, thank you for your message! Have you followed the installation instructions in the README? The layout template points to CSS and JS files in the assets directory, which have to be build by running Gulp first.

**Comment by Verbat** [comment]
In case you have not fixed this issue yet just updated your bower.json.
You need to replace **bootstrap.min.js** to **bootstrap.bundle.js**

The latest bootstrap 4 version needs Popper.js which is only included in the bootstrap bundle file.

**Comment by paulpoot** [comment]
@Verbat Thanks, that was indeed what caused this problem. I have pushed an update to update the dependencies and add popper.js. Should work out of the box now ;)
